MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 1
GENESIS_FORK_VERSION: 0x00000001
GENESIS_DELAY: 30
SECONDS_PER_SLOT: 6
SECONDS_PER_ETH1_BLOCK: 3
MIN_GENESIS_TIME: 1606824000
ETH1_FOLLOW_DISTANCE: 1
EJECTION_BALANCE: 16000000000